<?php

// Auto generated by Fusion News v3.9.6-p1

$fusion_id = 'v5Uk6wSAKGR69i0gmugT1KEOSS0j7z3q';
$datefor = 'Y-m-d H:i:s T';
$numofposts = 10;
$numofh = 5;
$bb = 1;
$ht = 1;
$post_per_day = 0;
$wfpost = 1;
$wfcom = 1;
$skin = 'fusion';
$smilies = 1;
$stfpop = 0;
$comallowbr = 1;
$stfwidth = 640;
$stfheight = 480;
$fslink = 'read more...';
$stflink = 'tell a friend';
$pclink = 'comments';
$fsnw = 0;
$cbflood = 1;
$floodtime = 30;
$comlength = 300;
$fullnewsw = 640;
$fullnewsh = 480;
$fullnewss = 1;
$stfresize = 1;
$stfscrolls = 1;
$fullnewsz = 1;
$htc = 0;
$smilcom = 1;
$bbc = 1;
$compop = 0;
$comscrolls = 1;
$comresize = 1;
$comheight = 480;
$comwidth = 640;
$uploads_active = 1;
$uploads_size = 1048576;
$uploads_ext = 'gif|jpg|jpeg|png|bmp';
$enable_rss = 1;
$link_headline_fullstory = 0;
$flip_news = 0;
$rss_title = '';
$rss_description = '';
$rss_encoding = 'utf-8';
$com_validation = 1;
$com_captcha = 1;
$news_pagination = 1;
$news_pagination_prv = '&lt;&lt; Prev';
$news_pagination_nxt = 'Next &gt;&gt;';
$news_pagination_numbers = 0;
$news_pagination_arrows = 1;
$ppp_date = 'jS F Y';
$comments_pages = 1;
$comments_per_page = 10;
$use_wysiwyg = 1;
$stf_captcha = 1;

?>