<?php defined("___ACCESS") or header("HTTP/1.1 403 Forbidden"); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="theme/default/main.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://code.jquery.com/jquery-1.5.2.min.js"></script>
<script type="text/javascript" src="js/main.js"></script>
<script type="text/javascript" src="js/update.js"></script>
<title><?php echo $site_name." - ".ucfirst($pagehandler->page); ?></title>
</head>

<body onload="javascript:getcontent('pages/<?php echo $pagehandler->page ?>.phtml?act=<?php echo $pagehandler->act; ?>', 'page')">
<div class="main">
	<div class="main_topleft"></div>
	<div id="players" class="main_topmiddle"></div>
	<div id="basicinfo" class="main_topright"></div>
	<div class="main_menu">
		<div class="button" onclick="navigate('news.php')"><span>News</span></div>
		<?php $pagehandler->GetButtons(); ?>
	</div>
	<div class="main_content">
		<div id="page" class="main_content_box"></div>
	</div>
</div>
<div class="version"><?php printf(_VERSION_, $version." by NotoriousPyro<br />\n"); printf(_LOADTIMER_, $loadtimer->GetLoadTime()); ?></div>
</body>
</html>