<?php

/**
 * This file is part of phpMCWeb.
 * phpMCWeb is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * phpMCWeb is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with phpMCWeb. If not, see <http://www.gnu.org/licenses/>.
 */

defined("___ACCESS") or header("HTTP/1.1 403 Forbidden");

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="theme/default/main.css" rel="stylesheet" type="text/css" />
<link href="theme/default/news.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://code.jquery.com/jquery-1.5.2.min.js"></script>
<script type="text/javascript" src="js/main.js"></script>
<script type="text/javascript" src="js/update.js"></script>
<title><?php echo $site_name." - News"; ?></title>
</head>

<body>
<div class="container">
	<div class="left">
		<div id="players"></div>
	</div>
	<div class="main">
		<div id="logo"></div>
		<div id="basicinfo"></div>
		<div id="menu">
			<div class="button" onclick="navigate('news.php')"><span>News</span></div>
			<?php $pagehandler->GetButtons(); ?>
		</div>
		<div id="content">
			<div id="page">
				<?php $fn_news_per_page = 3; require("news/news.php"); ?>
			</div>
		</div>
	</div>
	<div class="version"><?php

	// Please do not edit this line, if you wish to help develop phpMCWeb
	// then please get in touch with me at craigcrawford1988 AT gmail DOT com
	printf($phpmc["VERSION"].$phpmc["MAIN"]["LOADTIMER"], $loadtimer->GetLoadTime());

	?></div>
</div>
</body>
</html>