<?php 
define("___ACCESS", TRUE);
include("../config.php");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<body>
<iframe width="100%" height="561px" frameborder="0" src="<?php echo $dynmap; ?>"></iframe>
</body>
</html>
